name: CitySpeedNPM

on:
  push:
    branches: [ master ]


jobs:
  minify-and-publish-npm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'      
      - name: Minify dep
        run: npm i minify
      - name: sponge dep
        run: npm i sponge
      - name: minify js
        run: ./node_modules/.bin/minify speedtest.js | ./node_modules/.bin/sponge speedtest.js
      - name: minify css
        run: ./node_modules/.bin/minify speedtest.css | ./node_modules/.bin/sponge speedtest.css
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTO_TOKEN}}
